baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en"
title = "NoDoxa"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[markup.goldmark.renderer]
  unsafe = true

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-nodoxa.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo-nodoxa.svg"
    desktop_height = "36px"
    alt = "NoDoxa - Public Policy Consulting"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#0008C1"
    black = "#2f2f41"
    white = "#FDF0E0"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = ''

[menu]
  [[menu.main]]
    name = "Services"
    url = "/prestations/"
    weight = 1

  [[menu.main]]
    name = "Who are we?"
    url = "/who-are-we/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    name = "🇫🇷"
    url = "https://www.nodoxa.fr"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Legal Notice"
    url = "/legal-notice"
    weight = 1
